version: 0.2
phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - sudo ls /root
      - sudo cd /home/ubuntu
      - sudo apt-get update -y 
      - sudo apt-get install python3-pip apache2 libapache2-mod-wsgi-py3 -y 
      - sudo apt install apache2 -y 
      - sudo systemctl start  apache2
      - sudo systemctl enable apache2
      - sudo apt install python3-pip
      - sudo apt install python3-venv -y
      - sudo python3 -m venv demo-env
      - sudo source demo-env/bin/activate
      
      
  build:
    commands:
      - echo "Running all unit tests"
      - python manage.py test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
