version: 0.2

phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - whoami
      - pwd
      - sudo rm -rf /var/www/html/
  build:
    commands:
      - echo "Running all unit tests"
      
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
