version: 0.2
phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - cd /home/ubuntu
      - apt-get update -y 
      - apt-get install python3-pip apache2 libapache2-mod-wsgi-py3 -y 
      - apt install apache2 -y 
      - systemctl start  apache2
      - systemctl enable apache2
      - apt install python3-pip
      - apt install python3-venv -y
      - python3 -m venv demo-env
      - source demo-env/bin/activate
      
      
  build:
    commands:
      - echo "Running all unit tests"
      - python manage.py test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
