version: 0.2
phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - cp -rf  * /var/www/html
      - chown -R www-data:www-data /var/www/html/
      - sudo systemctl apache2 restart
      
      
  build:
    commands:
      - echo "Running all unit tests"
      - python manage.py test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
