version: 0.2
phases:
  pre_build:
    commands:
      - echo "Before running tests"   
      - sudo systemctl apache2 restart
      
      
  build:
    commands:
      - echo "Running all unit tests"
      - python3 manage.py test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
